behaviors:
  agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01          
    network_settings:
      normalize: true      # Normalizes coordinate variables
      hidden_units: 256    # Larger brain capacity for maze/wall navigation
      num_layers: 3        # Deeper layers to map movement choices
    max_steps: 2000000     # Extends training time to 2 million steps
    summary_freq: 10000    # Updates TensorBoard 5x faster than default
    time_horizon: 128
